### PR TITLE
[Oct 13] Staging --> production

### PR DESCRIPTION
**Pull request by meiqimichelle**
This PR sets up a push to production.

Improvements include:
- Link to Meetup instead of Google Cal
- Huge improvements to build process - makefile FTW
- Removes unnecessary javascript
- Adds framework for women techmaker page (still needs content)
- Adds variable for image directory in config
- Basic responsive work on homepage
- Removes long names for social media in nav

### CODE REVIEW

**Comment by dmsnell** [comment]
@meiqimichelle I'm a big fan of actually just rebasing **gh-pages** off of master instead of merging. If you look at the commit history, what we'll end up doing is replaying all of these 37 commits that we just did on **master**. Theoretically, we have tested the changes in **master** and don't have any need for the duplicated code history. Instead, **gh-pages** can act more like a tag into the main branch of the app - a delayed release of **master** to the world.

We can always revert a rebase if something happens too, just like when merging a PR.

**If we merge these changes**
merging

Here we run a parallel branch and duplicate the commits that exist in **master**. This is a little deceiving because we aren't exactly applying those commits to this branch intentionally; rather, what we are specifically doing is saying that we are happy with **master** at this point and want the **gh-pages** branch to now reflect that state.

**If we rebase**
screen shot 2015-10-14 at 1 56 22 am

Although I didn't draw it here because it's 2:19am and I'm tired :wink:, in this diagram the **gh-pages** tag now sits right on top of **master**. It occupies the same place and removes that long-running and parallel branch. This more closely reflects the semantic operation going on.

Some people will _never_ rebase in a `git` repo and there are reasons to scare people away. Nevertheless, used as they are intended it's a powerful way of keeping a clean history and removing needless complexity from the repository.

We would **never** rebase **master** because that would destroy the history and do all sorts of bad things; however, we don't actively develop inside of **gh-pages** (or shouldn't), so there's nothing to worry about there.

Rebasing a branch before a merge _into_ **master** also has value because it squashes the actual changes into that "change atom" that contains all the relevant modifications, but leaves out the less important history of how we got to those changes, but I digress....

**Rebasing**
If I look at `git log gh-pages` at the moment, it tells me that the branch is currently sitting at the commit with hash `0a78608605d1dc2c95432f0d70acd037f2a80002`. If I want to update it to the current master, I do this:

```bash
# Update the master branch from GitHub
git checkout master
git pull -p

# Rebase
git checkout gh-pages
git rebase master

# Push back to GitHub
# N.B. this is a history re-write, so we have to force
git push -f
```

This doesn't actually trigger a commit - it rewrites where the branch tip points to. If for some reason the :earth_americas: blows up after this, we can undo it by resetting to the previous commit:

```bash
git checkout gh-pages

# reset sets the branch tip to a specific "thing"
git reset --hard 0a78608605d1dc2c95432f0d70acd037f2a80002
git push -f
```

Ultimately this is about aesthetics on a project our size, but those can be important when we find ourselves debugging an issue, when it entered, and try to fix it. The commits, messages, and PRs already exist in **master**, so if it's the same to you I'd prefer to rebase **gh-pages**, but I don't care if we just merge.

My $0.02

**Comment by meiqimichelle** [comment]
@dmsnell I've rebased locally and resolved conflicts. The one thing I *don't* like about this approach is that I'm not sure there's a way for review -- as far as I know, I can't set up a pull request for review via rebase, right? Perhaps a way around this is to at least use version numbers for the site and memorialize releases. This isn't review, but at least the fact that we've updated the live site at certain points is recorded on GitHub in words. Thoughts?

**Comment by meiqimichelle** [comment]
Interesting. By rebasing locally and pushing this PR closed? Hrm.

**Comment by dmsnell** [comment]
@meiqimichelle you are correct about the review, but this has presumably already happened in **master**. It's really a strange way how we have **gh-pages** as the public source-of-truth and **master** as the development source-of-truth, but not all too dissimilar to projects with master and develop branches.

Honestly I mainly use rebasing on branches to wrap them up into a few commits and fewer merge changes before merging in to **master**, but personally I use the rebase in GitHub for the pages.

Tagging is a great idea and essentially free with `git`. In this case I created a phantom tag (that's not real vocabulary) by pasting the previous commit hash in this PR where the branch was before, which is the same thing a tag is except that it's given a name and stored in the `git` object store.

Another way that could have been nicer without rebasing would have been to simply merge a single commit instead of the 37 we had.

```bash
# Update master
git checkout master
git pull -p

# Merge
git checkout gh-pages
git merge master
```

Come to think of it, I'm not sure how that list of 37 commits got in here in the first place. How did you do that?

No harm done even if you don't like the rebase, though, right? Learning new things and exploring different patterns and figuring out how you like/want to do it? Sounds like a win to me!

**Comment by dmsnell** [comment]
Here's the graph as promised :smile: 

screen shot 2015-10-15 at 2 33 50 am

**Pull request merged**
