### PR TITLE
Update to 2016

### PR DESCRIPTION
**Pull request by msteinrueck**
Updated dates for 2016; indicated that the schedule online is from previous year and that we are still finalizing this year's schedule. Updated link to new registration form.

### CODE REVIEW

**Comment by dmsnell** [comment]
Thanks for the contribution @msteinrueck! I'd rather not eliminate the 2015 page, preferring instead to create a new page for 2016. Maybe we could rename the existing one to something like `womentechmakers-2015.html` and the new one `womentechmakers-2016.html`

We could update the permalinks to something like `/womentechmakers/` and `/womentechmakers/2015/`

It would also be awesome if we could convert that schedule into HTML. Right now it's not text-parseable/searchable. If you would like some help with that, please let us know.

Finally, we should probably make this page discoverable to visitors. We might need a big picture-link on the home page, but at a minimum this should exist in the site menus.

Nice work!

**Comment by msteinrueck** [comment]
Hi,

> Thanks for the contribution @msteinrueck 
> <https://github.com/msteinrueck>! I'd rather not eliminate the 2015 
> page, preferring instead to create a new page for 2016. Maybe we could 
> rename the existing one to something like |womentechmakers-2015.html| 
> and the new one |womentechmakers-2016.html|
>
> We could update the permalinks to something like |/womentechmakers/| 
> and |/womentechmakers/2015/|
>
That's a good idea, I'm ok with that! Can you take care of that or 
should I do it? I'm still new to github and the codefortucson site.
>
> It would also be awesome if we could convert that schedule into HTML. 
> Right now it's not text-parseable/searchable. If you would like some 
> help with that, please let us know.
>
That makes sense. I think it would be sufficient, if we do that for the 
new schedule, once it's available. I can do it then.
>
> Finally, we should probably make this page discoverable to visitors. 
> We might need a big picture-link on the home page, but at a minimum 
> this should exist in the site menus.
>
> Nice work!
>

**Comment by dmsnell** [comment]
> I'm still new to github and the codefortucson site.

welcome aboard 😄 

> Can you take care of that or
> should I do it?

I can't right now because I'm already distracted enough from my day-job. The permalink is set in the "front matter" at the top of the page file and Jekyll should take care of making it work. File renames can be done without worry.

Later tonight I should have some time hopefully, if you haven't figured it all out yourself by then :wink:

**Comment by msteinrueck** [comment]
I've created a new page that's archiving the old one. Can you approve this (and the archived page) now?
Thanks

**Comment by dmsnell** [comment]
> Can you approve this (and the archived page) now?

yes! :shipit:

**Pull request merged**
