### PR TITLE
Generates optimized versions of image assets

### PR DESCRIPTION
**Pull request by dmsnell**
This commit changes the way that image assets are handled in the final
site build. Previously, each developer was responsible for optimizing
all of the image assets himself or herself. Now, the image optimization
is handled automatically to relieve that burder and to encourage
consistency across the images.

Total image assets before this commit amounted to 2.8 MB, but after the
optimization only 552 KB - just 19% of what it started as.

Files are normally limited to have a longest edge of 1600px, but the size can be overwritten by specifying with the filename:

	- `image.jpg` --> use original size but limit to 1600px
	- `image-400.jpg` --> scale width to 400px and maintain aspect ratio
	- `image-x200.jpg` --> scale height to 200px and maintain aspect ratio
	- `image-400x200.jpg` --> force scale to 400x200 and butcher aspect ratio

The `source_assets` folder is the new place to save the original images and will also serve as the place in the future for all other uncompressed/unminified assets. To add a new file, add it to this directory but reference it as if it were residing in the normal `assets` folder. See the Readme for documentation.

Optimization is handled through the Makefile and occurs automatically.

**Changes to Makefile**
 - To run the local dev server run `make` or `make run` (`run` is the
   default target so you can leave it off).
 - To build the static files for the site but not start the server, run
   `make build`
 - To clear out the optimized assets (maybe to test or change the
   optimization parameters) run `make clean`
 - To only build the optimized images if they are missing or to update the ones whose source images have changed, run `make optimized-images`. This happens automatically on `make`, `make run`, and `make build`.

See `README.md` for normal development instructions.

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@dmsnell I'm running this branch locally, and the images seem a bit over-optimized (no longer crisp). The auto-image-optimizers I've seen remove unnecessary metadata from the image file, but don't touch image quality. How does this one work?

Also, I'm noticing that I used `png` where I should have used `svg`. I held out too long fearing cross-browser support for `svg` but this day and age it is totally fine. I'm happy to go through and switch out those files, which should help with total image size.

What do you think is a good next step?

**Comment by dmsnell** [comment]
@meiqimichelle interesting...this is of course why we do PRs :smile: 

The `png` images shouldn't visually change as `pngcrush` uses lossless techniques to do creative things with the encoding.

Right now I have `jpegoptim` set at 85% compression which is usually indistinguishable from 100%. I do see the eventbrite and meetup logo saved as JPG when they should be PNG. Can you give me an example image that has lost its sharpness?

On that note, it's trivial to bump up the quality, maybe 88% or 90% would be a good resting place. There could be something else going on too. We have been serving huge images and the browser has done all the scaling. Browsers are notoriously bad at downsizing images and you might actually be used to seeing an over-sharpened version of the image.

You can try this as a quick test:
 - Load the website on **master** and look at a "crisp" image
 - Open that image in Preview on your computer locally and compare

Does the website version look like the original?

As far as SVG goes I think we are fine. Let's get those changed out in another PR though, maybe after we get this one figured out?

**Comment by meiqimichelle** [comment]
Iiiiiinteresting. I notice it the most on the images that should have been svg/gif because they were really line/vector, and would have been better served as a non-raster. This is what got me thinking about switching to svg.

Let's see --
Here's an original image as I see it on my end:
screenshot 2015-10-08 17 59 51

And here's the optimized version:
screenshot 2015-10-08 17 59 45

My guess is that this has to do with retina display (where typically you serve an image@2x to take advantage of the high pixel density). I've always been curious about the best way to do this -- can we detect retina screens and only serve the larger images to them? Again, this is why I was thinking towards vectorizing what we can -- we can then better optimize the remainder since we wouldn't have to worry about the picky line images.

**Comment by dmsnell** [comment]
This particular image is only rendering at 70px according to the stylesheet (`.call-out-img { height: 70px; }`) and I think that's what you're seeing. I'm not sure why you're seeing that though. I see it being used in two places: on the home page and for projects that don't already have an associated image.

In the case of the homepage, does it not always render at 70px? or were you zooming in? In the case of projects, they should be using a higher-resolution image, specifically the 188px version which I included.

There is still no good way of dealing with retina assets. The [srcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) property is coming, but doesn't have good browser support still. SVG is a great option though and I believe that [it's support](http://caniuse.com/#feat=svg) is sufficient for mass-release.

**Comment by dmsnell** [comment]
Abandoning due to complexity of solution.

**Pull request closed without merging**
